#!/bin/bash

FILENAME=`basename $1`
HNAME=$FILENAME.h
HPATH=../impl/shader/$HNAME

# create header file
touch $HPATH

# output comment
echo "// Auto generated by convert.sh in shaders folder" > $HPATH

# output define
echo "#define $FILENAME \" \\" >> $HPATH

#output every line
sed '$!s/$/\\n \\/' $1 | sed '$s/$/\"/' | sed '1,$s/^/	/' >> $HPATH