/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_ShapeAnimation */

#ifndef _Included_com_wiyun_engine_chipmunk_ShapeAnimation
#define _Included_com_wiyun_engine_chipmunk_ShapeAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    nativeAddFrame
 * Signature: (FLcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_nativeAddFrame
  (JNIEnv *, jobject, jfloat, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    start
 * Signature: (Lcom/wiyun/engine/chipmunk/Shape;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    isLoop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_isLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    setLoop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_setLoop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    getDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    setDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_setDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/chipmunk/ShapeAnimation/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_setCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    isAutoSize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_isAutoSize
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_ShapeAnimation
 * Method:    setAutoSize
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_ShapeAnimation_setAutoSize
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
