/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_Segment */

#ifndef _Included_com_wiyun_engine_chipmunk_Segment
#define _Included_com_wiyun_engine_chipmunk_Segment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    init
 * Signature: (Lcom/wiyun/engine/chipmunk/Body;FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_init
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    setEndpoints
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_setEndpoints
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    getEndpoints
 * Signature: ([Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_getEndpoints
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    getNormal
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_getNormal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    getTransformedEndpoints
 * Signature: ([Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_getTransformedEndpoints
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    getTransformedNormal
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_getTransformedNormal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    setThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Segment_setThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Segment
 * Method:    getThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Segment_getThickness
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
