/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_GrooveJoint */

#ifndef _Included_com_wiyun_engine_chipmunk_GrooveJoint
#define _Included_com_wiyun_engine_chipmunk_GrooveJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_GrooveJoint
 * Method:    init
 * Signature: (Lcom/wiyun/engine/chipmunk/Body;Lcom/wiyun/engine/chipmunk/Body;FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_GrooveJoint_init
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_GrooveJoint
 * Method:    getAnchor2X
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_GrooveJoint_getAnchor2X
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_GrooveJoint
 * Method:    getAnchor2Y
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_GrooveJoint_getAnchor2Y
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_GrooveJoint
 * Method:    setAnchor2
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_GrooveJoint_setAnchor2
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
