/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_Body */

#ifndef _Included_com_wiyun_engine_chipmunk_Body
#define _Included_com_wiyun_engine_chipmunk_Body
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    nativeGetAnyShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_chipmunk_Body_nativeGetAnyShape
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setVelocityUpdater
 * Signature: (Lcom/wiyun/engine/chipmunk/Body/IVelocityUpdater;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setVelocityUpdater
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setPositionUpdater
 * Signature: (Lcom/wiyun/engine/chipmunk/Body/IPositionUpdater;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setPositionUpdater
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    init
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_init
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_wiyun_engine_chipmunk_Body_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setPosition
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setPosition
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getPositionX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getPositionX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getPositionY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getPositionY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setVelocity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setVelocity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getVelocityX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getVelocityX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getVelocityY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getVelocityY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setAngle
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setAngle
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getAngleUnitVectorX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getAngleUnitVectorX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getAngllUnitVectorY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getAngllUnitVectorY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setAngularVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setAngularVelocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getAngularVelocity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getAngularVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setTorque
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setTorque
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getTorque
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getTorque
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    updateVelocity
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_updateVelocity
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    updatePosition
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_updatePosition
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getMass
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getMass
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setMass
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setMass
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getMassInverse
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getMassInverse
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setMomentOfInertia
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setMomentOfInertia
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getMomentOfInertia
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getMomentOfInertia
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getMomentOfInertiaInverse
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getMomentOfInertiaInverse
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setForce
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setForce
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getForceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getForceX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getForceY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getForceY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    nativeApplyForce
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_nativeApplyForce
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    resetForces
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_resetForces
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setVelocityBias
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setVelocityBias
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getVelocityBiasX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getVelocityBiasX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getVelocityBiasY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getVelocityBiasY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setAngularVelocityBias
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setAngularVelocityBias
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getAngularVelocityBias
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getAngularVelocityBias
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getMaxVelocity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getMaxVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setMaxVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setMaxVelocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    getMaxAngularVelocity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Body_getMaxAngularVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    setMaxAngularVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_setMaxAngularVelocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    slew
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_slew
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_Body
 * Method:    applyImpulse
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_Body_applyImpulse
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
