/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_Arbiter */

#ifndef _Included_com_wiyun_engine_chipmunk_Arbiter
#define _Included_com_wiyun_engine_chipmunk_Arbiter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getContactPointX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getContactPointX
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getContactPointY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getContactPointY
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    isFirstContact
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_isFirstContact
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getTotalImpulseX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getTotalImpulseX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getTotalImpulseY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getTotalImpulseY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getTotalImpulseWithFrictionX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getTotalImpulseWithFrictionX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getTotalImpulseWithFrictionY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getTotalImpulseWithFrictionY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getContactPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getContactPointCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getNormalX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getNormalX
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getNormalY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getNormalY
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    nativeGetShapeA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_nativeGetShapeA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    nativeGetShapeB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_nativeGetShapeB
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_Arbiter
 * Method:    getTimeStamp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_chipmunk_Arbiter_getTimeStamp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
