/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_DampedRotarySpring */

#ifndef _Included_com_wiyun_engine_chipmunk_DampedRotarySpring
#define _Included_com_wiyun_engine_chipmunk_DampedRotarySpring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    init
 * Signature: (Lcom/wiyun/engine/chipmunk/Body;Lcom/wiyun/engine/chipmunk/Body;FFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_init
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    setTorqueUpdater
 * Signature: (Lcom/wiyun/engine/chipmunk/DampedRotarySpring/ITorqueUpdater;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_setTorqueUpdater
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    getRestAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_getRestAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    setRestAngle
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_setRestAngle
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    getStiffness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_getStiffness
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    setStiffness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_setStiffness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    getDamping
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_getDamping
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_DampedRotarySpring
 * Method:    setDamping
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_DampedRotarySpring_setDamping
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
