/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_chipmunk_GearJoint */

#ifndef _Included_com_wiyun_engine_chipmunk_GearJoint
#define _Included_com_wiyun_engine_chipmunk_GearJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_chipmunk_GearJoint
 * Method:    init
 * Signature: (Lcom/wiyun/engine/chipmunk/Body;Lcom/wiyun/engine/chipmunk/Body;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_GearJoint_init
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_GearJoint
 * Method:    getRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_GearJoint_getRatio
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_GearJoint
 * Method:    setRatio
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_GearJoint_setRatio
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_chipmunk_GearJoint
 * Method:    getPhase
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_chipmunk_GearJoint_getPhase
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_chipmunk_GearJoint
 * Method:    setPhase
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_chipmunk_GearJoint_setPhase
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
