/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_utils_VerletPoint */

#ifndef _Included_com_wiyun_engine_utils_VerletPoint
#define _Included_com_wiyun_engine_utils_VerletPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    setPosition
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_setPosition
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_update
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    applyGravity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_applyGravity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_utils_VerletPoint_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_utils_VerletPoint_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    attenuate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletPoint_attenuate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_utils_VerletPoint
 * Method:    nativeCopy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletPoint_nativeCopy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
