/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_utils_VerletRope */

#ifndef _Included_com_wiyun_engine_utils_VerletRope
#define _Included_com_wiyun_engine_utils_VerletRope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/opengl/Texture2D;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    reset
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_reset
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    update
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_update
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_draw
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getSticks
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_wiyun_engine_utils_VerletRope_getSticks
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    nativeGetStickAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_nativeGetStickAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getStickCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_getStickCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getPoints
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_wiyun_engine_utils_VerletRope_getPoints
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    nativeGetPointAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_nativeGetPointAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_getPointCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getCurrentLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_utils_VerletRope_getCurrentLength
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    rayCast
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_rayCast
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    setColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_setColor__Lcom_wiyun_engine_types_WYColor3B_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    setColor
 * Signature: (Lcom/wiyun/engine/types/WYColor4B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_setColor__Lcom_wiyun_engine_types_WYColor4B_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    getLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_utils_VerletRope_getLength
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    nativeSubRope
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletRope_nativeSubRope
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    isStretched
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_utils_VerletRope_isStretched
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletRope
 * Method:    changeLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletRope_changeLength
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
