/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_utils_BitmapFont */

#ifndef _Included_com_wiyun_engine_utils_BitmapFont
#define _Included_com_wiyun_engine_utils_BitmapFont
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_utils_BitmapFont_BFF_HGE
#define com_wiyun_engine_utils_BitmapFont_BFF_HGE 0L
#undef com_wiyun_engine_utils_BitmapFont_BFF_ANGELCODE_TXT
#define com_wiyun_engine_utils_BitmapFont_BFF_ANGELCODE_TXT 1L
#undef com_wiyun_engine_utils_BitmapFont_BFF_ANGELCODE_XML
#define com_wiyun_engine_utils_BitmapFont_BFF_ANGELCODE_XML 2L
/*
 * Class:     com_wiyun_engine_utils_BitmapFont
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_BitmapFont_nativeInit__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_utils_BitmapFont
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;ZIF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_BitmapFont_nativeInit__Ljava_lang_String_2ZIF
  (JNIEnv *, jobject, jstring, jboolean, jint, jfloat);

/*
 * Class:     com_wiyun_engine_utils_BitmapFont
 * Method:    unloadFont
 * Signature: (Lcom/wiyun/engine/utils/BitmapFont;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_BitmapFont_unloadFont
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
