/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_utils_VerletStick */

#ifndef _Included_com_wiyun_engine_utils_VerletStick
#define _Included_com_wiyun_engine_utils_VerletStick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_utils_VerletStick
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/utils/VerletPoint;Lcom/wiyun/engine/utils/VerletPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletStick_nativeInit
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletStick
 * Method:    contract
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_VerletStick_contract
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_utils_VerletStick
 * Method:    nativeGetPointA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletStick_nativeGetPointA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletStick
 * Method:    nativeGetPointB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_utils_VerletStick_nativeGetPointB
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletStick
 * Method:    getLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_utils_VerletStick_getLength
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_utils_VerletStick
 * Method:    getCurrentLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_utils_VerletStick_getCurrentLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
