/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_astar_AStarMap */

#ifndef _Included_com_wiyun_engine_astar_AStarMap
#define _Included_com_wiyun_engine_astar_AStarMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_astar_AStarMap
 * Method:    blockTile
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_astar_AStarMap_blockTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_astar_AStarMap
 * Method:    freeTile
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_astar_AStarMap_freeTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_astar_AStarMap
 * Method:    isBlockedAt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_astar_AStarMap_isBlockedAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_astar_AStarMap
 * Method:    nativeGetTileAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_astar_AStarMap_nativeGetTileAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_astar_AStarMap
 * Method:    isValidTile
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_astar_AStarMap_isValidTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_astar_AStarMap
 * Method:    getStepG
 * Signature: (Lcom/wiyun/engine/astar/AStarTile;Lcom/wiyun/engine/astar/AStarTile;)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_astar_AStarMap_getStepG
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
