/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_astar_RectAStarMap */

#ifndef _Included_com_wiyun_engine_astar_RectAStarMap
#define _Included_com_wiyun_engine_astar_RectAStarMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_astar_RectAStarMap
 * Method:    nativeInit
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_astar_RectAStarMap_nativeInit
  (JNIEnv *, jobject, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
