/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_lua_Lua */

#ifndef _Included_com_wiyun_engine_lua_Lua
#define _Included_com_wiyun_engine_lua_Lua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_init
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    execute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_execute__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    execute
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_execute__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    execute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_execute__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    setGlobal
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_setGlobal__Ljava_lang_String_2Ljava_lang_Object_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jobject, jstring);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    setGlobal
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_setGlobal__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    setGlobal
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_setGlobal__Ljava_lang_String_2F
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    setGlobal
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_lua_Lua_setGlobal__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    getGlobalObject
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_lua_Lua_getGlobalObject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    getGlobalInt
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_lua_Lua_getGlobalInt
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    getGlobalFloat
 * Signature: (Ljava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_lua_Lua_getGlobalFloat
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     com_wiyun_engine_lua_Lua
 * Method:    getGlobalString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_lua_Lua_getGlobalString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
