#if ANDROID

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_utils_ImagePickerActivity */

#ifndef _Included_com_wiyun_engine_utils_ImagePickerActivity
#define _Included_com_wiyun_engine_utils_ImagePickerActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_utils_ImagePickerActivity_ID_CANCEL
#define com_wiyun_engine_utils_ImagePickerActivity_ID_CANCEL 1000L
#undef com_wiyun_engine_utils_ImagePickerActivity_ID_CAMERA
#define com_wiyun_engine_utils_ImagePickerActivity_ID_CAMERA 1001L
#undef com_wiyun_engine_utils_ImagePickerActivity_ID_OK
#define com_wiyun_engine_utils_ImagePickerActivity_ID_OK 1002L
/*
 * Class:     com_wiyun_engine_utils_ImagePickerActivity
 * Method:    onImagePicked
 * Signature: (II[BIIZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_ImagePickerActivity_onImagePicked
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_wiyun_engine_utils_ImagePickerActivity
 * Method:    onImagePickCancelled
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_utils_ImagePickerActivity_onImagePickCancelled
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

#endif // #if ANDROID