/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_SplitColsTransition */

#ifndef _Included_com_wiyun_engine_transitions_SplitColsTransition
#define _Included_com_wiyun_engine_transitions_SplitColsTransition
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_transitions_SplitColsTransition_INVALID_TAG
#define com_wiyun_engine_transitions_SplitColsTransition_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_transitions_SplitColsTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_SplitColsTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
