/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_FlipYTransition */

#ifndef _Included_com_wiyun_engine_transitions_FlipYTransition
#define _Included_com_wiyun_engine_transitions_FlipYTransition
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_transitions_FlipYTransition_INVALID_TAG
#define com_wiyun_engine_transitions_FlipYTransition_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_transitions_FlipYTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_FlipYTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
