/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_CrossFadeTransition */

#ifndef _Included_com_wiyun_engine_transitions_CrossFadeTransition
#define _Included_com_wiyun_engine_transitions_CrossFadeTransition
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_transitions_CrossFadeTransition_INVALID_TAG
#define com_wiyun_engine_transitions_CrossFadeTransition_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_transitions_CrossFadeTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_CrossFadeTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
