/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_ZoomFlipXTransition */

#ifndef _Included_com_wiyun_engine_transitions_ZoomFlipXTransition
#define _Included_com_wiyun_engine_transitions_ZoomFlipXTransition
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_transitions_ZoomFlipXTransition_INVALID_TAG
#define com_wiyun_engine_transitions_ZoomFlipXTransition_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_transitions_ZoomFlipXTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;ZF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_ZoomFlipXTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject, jboolean, jfloat);

#ifdef __cplusplus
}
#endif
#endif
