/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition */

#ifndef _Included_com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition
#define _Included_com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition_INVALID_TAG
#define com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_RightTopTilesShrinkOutTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
