/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_RadialCCWTransition */

#ifndef _Included_com_wiyun_engine_transitions_RadialCCWTransition
#define _Included_com_wiyun_engine_transitions_RadialCCWTransition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_transitions_RadialCCWTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_RadialCCWTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
