/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_transitions_ClipInTransition */

#ifndef _Included_com_wiyun_engine_transitions_ClipInTransition
#define _Included_com_wiyun_engine_transitions_ClipInTransition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_transitions_ClipInTransition
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/nodes/Scene;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_transitions_ClipInTransition_nativeInit
  (JNIEnv *, jobject, jfloat, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
