/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_skeleton_Skeleton */

#ifndef _Included_com_wiyun_engine_skeleton_Skeleton
#define _Included_com_wiyun_engine_skeleton_Skeleton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_skeleton_Skeleton
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_nativeStart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
