/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_opengl_TextureManager */

#ifndef _Included_com_wiyun_engine_opengl_TextureManager
#define _Included_com_wiyun_engine_opengl_TextureManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGBA8888
#define com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGBA8888 0L
#undef com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGB565
#define com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGB565 1L
#undef com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGBA4444
#define com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGBA4444 2L
#undef com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGBA5551
#define com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_RGBA5551 3L
#undef com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_A8
#define com_wiyun_engine_opengl_TextureManager_TEXTURE_PIXEL_FORMAT_A8 4L
/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    nativeGetInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_TextureManager_nativeGetInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_TextureManager_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    getTextureCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_TextureManager_getTextureCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    removeAllTextures
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_TextureManager_removeAllTextures
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    removeTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_TextureManager_removeTexture__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    removeTexture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_TextureManager_removeTexture__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    removeTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_TextureManager_removeTexture__Lcom_wiyun_engine_opengl_Texture2D_2Z
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    setTexturePixelFormat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_TextureManager_setTexturePixelFormat
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_opengl_TextureManager
 * Method:    getTexturePixelFormat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_TextureManager_getTexturePixelFormat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
