/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_CustomColorFilter */

#ifndef _Included_com_wiyun_engine_filters_CustomColorFilter
#define _Included_com_wiyun_engine_filters_CustomColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_CustomColorFilter
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/filters/CustomColorFilter/IColorFilterDelegate;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_CustomColorFilter_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_filters_CustomColorFilter
 * Method:    setDelegate
 * Signature: (Lcom/wiyun/engine/filters/CustomColorFilter/IColorFilterDelegate;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_CustomColorFilter_setDelegate
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
