/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_ColorFilter */

#ifndef _Included_com_wiyun_engine_filters_ColorFilter
#define _Included_com_wiyun_engine_filters_ColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_ColorFilter
 * Method:    apply
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_ColorFilter_apply
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
