/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_LightingColorFilter */

#ifndef _Included_com_wiyun_engine_filters_LightingColorFilter
#define _Included_com_wiyun_engine_filters_LightingColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_LightingColorFilter
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_LightingColorFilter_nativeInit
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
