/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_BlurColorFilter */

#ifndef _Included_com_wiyun_engine_filters_BlurColorFilter
#define _Included_com_wiyun_engine_filters_BlurColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_BlurColorFilter
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_BlurColorFilter_nativeInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_filters_BlurColorFilter
 * Method:    setRadius
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_BlurColorFilter_setRadius
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_filters_BlurColorFilter
 * Method:    getRadius
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_filters_BlurColorFilter_getRadius
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
