/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_ColorMatrixColorFilter */

#ifndef _Included_com_wiyun_engine_filters_ColorMatrixColorFilter
#define _Included_com_wiyun_engine_filters_ColorMatrixColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_ColorMatrixColorFilter
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/ColorMatrix;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_ColorMatrixColorFilter_nativeInit
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
