/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_AreaColorFilter */

#ifndef _Included_com_wiyun_engine_filters_AreaColorFilter
#define _Included_com_wiyun_engine_filters_AreaColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    mapPoint
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_mapPoint
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    removePoint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_removePoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    mapLine
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_mapLine
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    removeLine
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_removeLine
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    mapRect
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_mapRect
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    removeRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_removeRect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    mapCircle
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_mapCircle
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_AreaColorFilter
 * Method:    removeCircle
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_AreaColorFilter_removeCircle
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
