/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_MappingColorFilter */

#ifndef _Included_com_wiyun_engine_filters_MappingColorFilter
#define _Included_com_wiyun_engine_filters_MappingColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_MappingColorFilter
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_MappingColorFilter_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_filters_MappingColorFilter
 * Method:    mapColor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_MappingColorFilter_mapColor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_MappingColorFilter
 * Method:    unmapColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_MappingColorFilter_unmapColor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
