/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_DropShadowColorFilter */

#ifndef _Included_com_wiyun_engine_filters_DropShadowColorFilter
#define _Included_com_wiyun_engine_filters_DropShadowColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_nativeInit
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    setRadius
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_setRadius
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    getRadius
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_getRadius
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    setOpacity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_setOpacity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    getOpacity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_getOpacity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    setHighlightRadius
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_setHighlightRadius
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_filters_DropShadowColorFilter
 * Method:    getHighlightRadius
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_filters_DropShadowColorFilter_getHighlightRadius
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
