/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_filters_CombineColorFilter */

#ifndef _Included_com_wiyun_engine_filters_CombineColorFilter
#define _Included_com_wiyun_engine_filters_CombineColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_filters_CombineColorFilter
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/ColorFilter;[Lcom/wiyun/engine/opengl/ColorFilter;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_CombineColorFilter_nativeInit
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_wiyun_engine_filters_CombineColorFilter
 * Method:    addFilter
 * Signature: (Lcom/wiyun/engine/opengl/ColorFilter;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_filters_CombineColorFilter_addFilter
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
