/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_collision_CircleShape */

#ifndef _Included_com_wiyun_engine_box2d_collision_CircleShape
#define _Included_com_wiyun_engine_box2d_collision_CircleShape
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_collision_CircleShape_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_collision_CircleShape_TYPE_UNKNOWN -1L
#undef com_wiyun_engine_box2d_collision_CircleShape_TYPE_CIRCLE
#define com_wiyun_engine_box2d_collision_CircleShape_TYPE_CIRCLE 0L
#undef com_wiyun_engine_box2d_collision_CircleShape_TYPE_EDGE
#define com_wiyun_engine_box2d_collision_CircleShape_TYPE_EDGE 1L
#undef com_wiyun_engine_box2d_collision_CircleShape_TYPE_POLYGON
#define com_wiyun_engine_box2d_collision_CircleShape_TYPE_POLYGON 2L
#undef com_wiyun_engine_box2d_collision_CircleShape_TYPE_LOOP
#define com_wiyun_engine_box2d_collision_CircleShape_TYPE_LOOP 3L
/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    setPosition
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_setPosition
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    nativeGetPosition
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_nativeGetPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    getSupport
 * Signature: (FF)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_getSupport
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    nativeGetSupportVertex
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_nativeGetSupportVertex
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    getVertexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_getVertexCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_CircleShape
 * Method:    nativeGetVertex
 * Signature: (Lcom/wiyun/engine/types/WYPoint;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_CircleShape_nativeGetVertex
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
