/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_collision_Shape */

#ifndef _Included_com_wiyun_engine_box2d_collision_Shape
#define _Included_com_wiyun_engine_box2d_collision_Shape
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_collision_Shape_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_collision_Shape_TYPE_UNKNOWN -1L
#undef com_wiyun_engine_box2d_collision_Shape_TYPE_CIRCLE
#define com_wiyun_engine_box2d_collision_Shape_TYPE_CIRCLE 0L
#undef com_wiyun_engine_box2d_collision_Shape_TYPE_EDGE
#define com_wiyun_engine_box2d_collision_Shape_TYPE_EDGE 1L
#undef com_wiyun_engine_box2d_collision_Shape_TYPE_POLYGON
#define com_wiyun_engine_box2d_collision_Shape_TYPE_POLYGON 2L
#undef com_wiyun_engine_box2d_collision_Shape_TYPE_LOOP
#define com_wiyun_engine_box2d_collision_Shape_TYPE_LOOP 3L
/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    copy
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/World;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_collision_Shape_copy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_collision_Shape_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_Shape_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    setRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_Shape_setRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    getRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_collision_Shape_getRadius
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    getChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_collision_Shape_getChildCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    testPoint
 * Signature: (Lcom/wiyun/engine/box2d/common/Transform;Lcom/wiyun/engine/types/WYPoint;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_collision_Shape_testPoint
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    nativeRayCast
 * Signature: (Lcom/wiyun/engine/box2d/collision/RayCastOutput;Lcom/wiyun/engine/box2d/collision/RayCastInput;Lcom/wiyun/engine/box2d/common/Transform;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_Shape_nativeRayCast
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    nativeComputeAABB
 * Signature: (Lcom/wiyun/engine/box2d/collision/AABB;Lcom/wiyun/engine/box2d/common/Transform;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_Shape_nativeComputeAABB
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_collision_Shape
 * Method:    nativeComputeMass
 * Signature: (Lcom/wiyun/engine/box2d/collision/MassData;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_Shape_nativeComputeMass
  (JNIEnv *, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
