/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_collision_PolygonShape */

#ifndef _Included_com_wiyun_engine_box2d_collision_PolygonShape
#define _Included_com_wiyun_engine_box2d_collision_PolygonShape
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_collision_PolygonShape_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_collision_PolygonShape_TYPE_UNKNOWN -1L
#undef com_wiyun_engine_box2d_collision_PolygonShape_TYPE_CIRCLE
#define com_wiyun_engine_box2d_collision_PolygonShape_TYPE_CIRCLE 0L
#undef com_wiyun_engine_box2d_collision_PolygonShape_TYPE_EDGE
#define com_wiyun_engine_box2d_collision_PolygonShape_TYPE_EDGE 1L
#undef com_wiyun_engine_box2d_collision_PolygonShape_TYPE_POLYGON
#define com_wiyun_engine_box2d_collision_PolygonShape_TYPE_POLYGON 2L
#undef com_wiyun_engine_box2d_collision_PolygonShape_TYPE_LOOP
#define com_wiyun_engine_box2d_collision_PolygonShape_TYPE_LOOP 3L
/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    setVertices
 * Signature: ([Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_setVertices
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    setAsBox
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_setAsBox__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    setAsBox
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_setAsBox__FFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    getVertexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_getVertexCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    nativeGetVertex
 * Signature: (Lcom/wiyun/engine/types/WYPoint;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_nativeGetVertex
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    nativeGetCentroid
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_nativeGetCentroid
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_PolygonShape
 * Method:    validate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_collision_PolygonShape_validate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
