/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_collision_EdgeShape */

#ifndef _Included_com_wiyun_engine_box2d_collision_EdgeShape
#define _Included_com_wiyun_engine_box2d_collision_EdgeShape
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_collision_EdgeShape_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_collision_EdgeShape_TYPE_UNKNOWN -1L
#undef com_wiyun_engine_box2d_collision_EdgeShape_TYPE_CIRCLE
#define com_wiyun_engine_box2d_collision_EdgeShape_TYPE_CIRCLE 0L
#undef com_wiyun_engine_box2d_collision_EdgeShape_TYPE_EDGE
#define com_wiyun_engine_box2d_collision_EdgeShape_TYPE_EDGE 1L
#undef com_wiyun_engine_box2d_collision_EdgeShape_TYPE_POLYGON
#define com_wiyun_engine_box2d_collision_EdgeShape_TYPE_POLYGON 2L
#undef com_wiyun_engine_box2d_collision_EdgeShape_TYPE_LOOP
#define com_wiyun_engine_box2d_collision_EdgeShape_TYPE_LOOP 3L
/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    setEndpoints
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_setEndpoints
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    nativeGetEndpoint1
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_nativeGetEndpoint1
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    nativeGetEndpoint2
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_nativeGetEndpoint2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    hasAdjacentVertex1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_hasAdjacentVertex1
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    hasAdjacentVertex2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_hasAdjacentVertex2
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    nativeGetAdjacentVertex1
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_nativeGetAdjacentVertex1
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_collision_EdgeShape
 * Method:    nativeGetAdjacentVertex2
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_collision_EdgeShape_nativeGetAdjacentVertex2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
