/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine */

#ifndef _Included_com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine
#define _Included_com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine_RENDERMODE_WHEN_DIRTY
#define com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine_RENDERMODE_WHEN_DIRTY 0L
#undef com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine_RENDERMODE_CONTINUOUSLY
#define com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine_RENDERMODE_CONTINUOUSLY 1L
/*
 * Class:     com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_SnowEngine
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_livewallpaper_WiEngineLiveWallpaperService_00024SnowEngine_nativeStart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
