/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_tmx_TMXLayer */

#ifndef _Included_com_wiyun_engine_tmx_TMXLayer
#define _Included_com_wiyun_engine_tmx_TMXLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getLayerWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getLayerWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getLayerHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getLayerHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getTileWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getTileWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getTileHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getTileHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getGidAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getGidAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getGids
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getGids
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    nativeTileAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_nativeTileAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    removeTile
 * Signature: (Lcom/wiyun/engine/nodes/SpriteEx;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_removeTile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    removeTileAt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_removeTileAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    setTileAt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_setTileAt
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    updateTileAt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_updateTileAt
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getProperty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    nativeGetPositionAt
 * Signature: (IILcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_nativeGetPositionAt
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    nativeGetTileCoordinateAt
 * Signature: (FFLcom/wiyun/engine/types/WYDimension;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_nativeGetTileCoordinateAt
  (JNIEnv *, jobject, jfloat, jfloat, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXLayer_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXLayer
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXLayer_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
