/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_tmx_TMXObjectGroup */

#ifndef _Included_com_wiyun_engine_tmx_TMXObjectGroup
#define _Included_com_wiyun_engine_tmx_TMXObjectGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    addProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_addProperty
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getProperty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    nativeGetObject
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_nativeGetObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    nativeGetObjectAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_nativeGetObjectAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getObjectCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getObjectCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    setOffsetX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_setOffsetX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getOffsetX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getOffsetX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    setOffsetY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_setOffsetY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getOffsetY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getOffsetY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    getOpacity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_getOpacity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_tmx_TMXObjectGroup
 * Method:    setOpacity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_tmx_TMXObjectGroup_setOpacity
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
