/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_controllers_ConstantForceController */

#ifndef _Included_com_wiyun_engine_box2d_controllers_ConstantForceController
#define _Included_com_wiyun_engine_box2d_controllers_ConstantForceController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_controllers_ConstantForceController
 * Method:    setForce
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_ConstantForceController_setForce
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_ConstantForceController
 * Method:    nativeGetForce
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_ConstantForceController_nativeGetForce
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
