/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_controllers_GravityController */

#ifndef _Included_com_wiyun_engine_box2d_controllers_GravityController
#define _Included_com_wiyun_engine_box2d_controllers_GravityController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_controllers_GravityController
 * Method:    setGravitationalConstant
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_GravityController_setGravitationalConstant
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_GravityController
 * Method:    getGravitationalConstant
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_controllers_GravityController_getGravitationalConstant
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_GravityController
 * Method:    setProportionalToInvRadius
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_GravityController_setProportionalToInvRadius
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_controllers_GravityController
 * Method:    isProportionalToInvRadius
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_controllers_GravityController_isProportionalToInvRadius
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
