/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_controllers_ConstantForceControllerDef */

#ifndef _Included_com_wiyun_engine_box2d_controllers_ConstantForceControllerDef
#define _Included_com_wiyun_engine_box2d_controllers_ConstantForceControllerDef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_controllers_ConstantForceControllerDef
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_ConstantForceControllerDef_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_ConstantForceControllerDef
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_ConstantForceControllerDef_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_ConstantForceControllerDef
 * Method:    setForce
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_ConstantForceControllerDef_setForce
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_ConstantForceControllerDef
 * Method:    nativeGetForce
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_ConstantForceControllerDef_nativeGetForce
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
