/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_controllers_BuoyancyController */

#ifndef _Included_com_wiyun_engine_box2d_controllers_BuoyancyController
#define _Included_com_wiyun_engine_box2d_controllers_BuoyancyController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setNormal
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setNormal
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    nativeGetNormal
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_nativeGetNormal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    getOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_getOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    getDensity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_getDensity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setDensity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setDensity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setVelocity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setVelocity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    nativeGetVelocity
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_nativeGetVelocity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    getLinearDrag
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_getLinearDrag
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setLinearDrag
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setLinearDrag
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    getAngularDrag
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_getAngularDrag
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setAngularDrag
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setAngularDrag
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    isUseDensity
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_isUseDensity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setUseDensity
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setUseDensity
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    isUseWorldGravity
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_isUseWorldGravity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setUseWorldGravity
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setUseWorldGravity
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    setGravity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_setGravity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_controllers_BuoyancyController
 * Method:    nativeGetGravity
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_controllers_BuoyancyController_nativeGetGravity
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
