/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_contacts_ContactEdge */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_contacts_ContactEdge
#define _Included_com_wiyun_engine_box2d_dynamics_contacts_ContactEdge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_ContactEdge
 * Method:    nativeGetBody
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_ContactEdge_nativeGetBody
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_ContactEdge
 * Method:    nativeGetContact
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_ContactEdge_nativeGetContact
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_ContactEdge
 * Method:    nativeGetNext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_ContactEdge_nativeGetNext
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_ContactEdge
 * Method:    nativeGetPrev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_ContactEdge_nativeGetPrev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
