/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_contacts_Contact */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_contacts_Contact
#define _Included_com_wiyun_engine_box2d_dynamics_contacts_Contact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    nativeGetManifold
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_nativeGetManifold
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    nativeGetFixtureA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_nativeGetFixtureA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    nativeGetFixtureB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_nativeGetFixtureB
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_setEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    isTouching
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_isTouching
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    nativeGetNext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_nativeGetNext
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    getChildIndexA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_getChildIndexA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    getChildIndexB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_getChildIndexB
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    nativeEvaluate
 * Signature: (Lcom/wiyun/engine/box2d/common/Transform;Lcom/wiyun/engine/box2d/common/Transform;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_nativeEvaluate
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    setFriction
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_setFriction
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    getFriction
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_getFriction
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    resetFriction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_resetFriction
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    setRestitution
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_setRestitution
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    getRestitution
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_getRestitution
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_contacts_Contact
 * Method:    resetRestitution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_contacts_Contact_resetRestitution
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
