/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_Animate */

#ifndef _Included_com_wiyun_engine_actions_Animate
#define _Included_com_wiyun_engine_actions_Animate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_Animate
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/nodes/Node/IAnimation;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Animate_nativeInit
  (JNIEnv *, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
