/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_TintTo */

#ifndef _Included_com_wiyun_engine_actions_TintTo
#define _Included_com_wiyun_engine_actions_TintTo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_TintTo
 * Method:    nativeInit
 * Signature: (FIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_TintTo_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
