/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ReverseTime */

#ifndef _Included_com_wiyun_engine_actions_ReverseTime
#define _Included_com_wiyun_engine_actions_ReverseTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_ReverseTime
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/actions/FiniteTimeAction;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ReverseTime_nativeInit
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
