/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_TintBy */

#ifndef _Included_com_wiyun_engine_actions_TintBy
#define _Included_com_wiyun_engine_actions_TintBy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_TintBy
 * Method:    nativeInit
 * Signature: (FIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_TintBy_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
