/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ProgressTo */

#ifndef _Included_com_wiyun_engine_actions_ProgressTo
#define _Included_com_wiyun_engine_actions_ProgressTo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_ProgressTo
 * Method:    nativeInit
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ProgressTo_nativeInit
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
