/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_CallFunc */

#ifndef _Included_com_wiyun_engine_actions_CallFunc
#define _Included_com_wiyun_engine_actions_CallFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_CallFunc
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/utils/TargetSelector;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_CallFunc_nativeInit
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
