/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_Action */

#ifndef _Included_com_wiyun_engine_actions_Action
#define _Included_com_wiyun_engine_actions_Action
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    getTag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_Action_getTag
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    setTag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Action_setTag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    nativeGetTarget
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_Action_nativeGetTarget
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/actions/Action/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Action_setCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    nativeCopy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_Action_nativeCopy
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    nativeReverse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_Action_nativeReverse
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    start
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Action_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Action_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    isDone
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_actions_Action_isDone
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    step
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Action_step
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_actions_Action
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Action_update
  (JNIEnv *, jobject, jfloat);

JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_actions_Action_isPaused
  (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_actions_Action_isRunning
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
