/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_Hide */

#ifndef _Included_com_wiyun_engine_actions_Hide
#define _Included_com_wiyun_engine_actions_Hide
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_Hide
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Hide_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
