/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_FadeIn */

#ifndef _Included_com_wiyun_engine_actions_FadeIn
#define _Included_com_wiyun_engine_actions_FadeIn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_FadeIn
 * Method:    nativeInit
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_FadeIn_nativeInit
  (JNIEnv *, jobject, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
