/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_MoveByAngle */

#ifndef _Included_com_wiyun_engine_actions_MoveByAngle
#define _Included_com_wiyun_engine_actions_MoveByAngle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_MoveByAngle
 * Method:    nativeInit
 * Signature: (FII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByAngle_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint);

/*
 * Class:     com_wiyun_engine_actions_MoveByAngle
 * Method:    setPinPoint
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByAngle_setPinPoint
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_actions_MoveByAngle
 * Method:    nativeGetPinPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByAngle_nativeGetPinPoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByAngle
 * Method:    clearPinPoint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByAngle_clearPinPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByAngle
 * Method:    setPinAngleDelta
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByAngle_setPinAngleDelta
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_actions_MoveByAngle
 * Method:    getPinAngleDelta
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_actions_MoveByAngle_getPinAngleDelta
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
