/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_Follow */

#ifndef _Included_com_wiyun_engine_actions_Follow
#define _Included_com_wiyun_engine_actions_Follow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_Follow
 * Method:    nativeInit
 * Signature: (FIIZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Follow_nativeInit
  (JNIEnv *, jobject, jobject, jint , jint , jint, jint);

#ifdef __cplusplus
}
#endif
#endif
