/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ClipOut */

#ifndef _Included_com_wiyun_engine_actions_ClipOut
#define _Included_com_wiyun_engine_actions_ClipOut
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_actions_ClipOut_LEFT_TO_RIGHT
#define com_wiyun_engine_actions_ClipOut_LEFT_TO_RIGHT 0L
#undef com_wiyun_engine_actions_ClipOut_RIGHT_TO_LEFT
#define com_wiyun_engine_actions_ClipOut_RIGHT_TO_LEFT 1L
#undef com_wiyun_engine_actions_ClipOut_TOP_TO_BOTTOM
#define com_wiyun_engine_actions_ClipOut_TOP_TO_BOTTOM 2L
#undef com_wiyun_engine_actions_ClipOut_BOTTOM_TO_TOP
#define com_wiyun_engine_actions_ClipOut_BOTTOM_TO_TOP 3L
/*
 * Class:     com_wiyun_engine_actions_ClipOut
 * Method:    nativeInit
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ClipOut_nativeInit
  (JNIEnv *, jobject, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
