/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_Blink */

#ifndef _Included_com_wiyun_engine_actions_Blink
#define _Included_com_wiyun_engine_actions_Blink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_Blink
 * Method:    nativeInit
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Blink_nativeInit
  (JNIEnv *, jobject, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
