/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_Repeat */

#ifndef _Included_com_wiyun_engine_actions_Repeat
#define _Included_com_wiyun_engine_actions_Repeat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_Repeat
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/actions/FiniteTimeAction;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_Repeat_nativeInit
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
