/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_MoveByPath */

#ifndef _Included_com_wiyun_engine_actions_MoveByPath
#define _Included_com_wiyun_engine_actions_MoveByPath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    addPoint
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_addPoint
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    getPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_MoveByPath_getPointCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    getPoints
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_wiyun_engine_actions_MoveByPath_getPoints
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    setAutoRotate
 * Signature: (ZF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_setAutoRotate
  (JNIEnv *, jobject, jboolean, jfloat);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    setPinPoint
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_setPinPoint
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    nativeGetPinPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_nativeGetPinPoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    clearPinPoint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_clearPinPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    setPinAngleDelta
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_MoveByPath_setPinAngleDelta
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_actions_MoveByPath
 * Method:    getPinAngleDelta
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_actions_MoveByPath_getPinAngleDelta
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
