/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ScaleTo */

#ifndef _Included_com_wiyun_engine_actions_ScaleTo
#define _Included_com_wiyun_engine_actions_ScaleTo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_ScaleTo
 * Method:    nativeInit
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ScaleTo_nativeInit
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
