/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_JumpTo */

#ifndef _Included_com_wiyun_engine_actions_JumpTo
#define _Included_com_wiyun_engine_actions_JumpTo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_JumpTo
 * Method:    nativeInit
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_JumpTo_nativeInit
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
