/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_SPXSprite */

#ifndef _Included_com_wiyun_engine_afcanim_SPXSprite
#define _Included_com_wiyun_engine_afcanim_SPXSprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_SPXSprite
 * Method:    nativeInit
 * Signature: (ILcom/wiyun/engine/opengl/Texture2D;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_SPXSprite_nativeInit__ILcom_wiyun_engine_opengl_Texture2D_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_SPXSprite
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;ZLcom/wiyun/engine/opengl/Texture2D;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_SPXSprite_nativeInit__Ljava_lang_String_2ZLcom_wiyun_engine_opengl_Texture2D_2I
  (JNIEnv *, jobject, jstring, jboolean, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
