/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_AFCFrame */

#ifndef _Included_com_wiyun_engine_afcanim_AFCFrame
#define _Included_com_wiyun_engine_afcanim_AFCFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    getClipCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_getClipCount__
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    getClipCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_getClipCount__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    nativeGetClipAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_nativeGetClipAt__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    getDelay
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_getDelay
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    nativeGetIncrementation
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_nativeGetIncrementation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    nativeGetClipAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_nativeGetClipAt__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    isFlipX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_isFlipX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCFrame
 * Method:    isFlipY
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCFrame_isFlipY
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
