/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_AFCSprite */

#ifndef _Included_com_wiyun_engine_afcanim_AFCSprite
#define _Included_com_wiyun_engine_afcanim_AFCSprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetAnimationAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetAnimationAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getAnimationCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getAnimationCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getImageCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getImageCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    playAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_playAnimation__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    playAnimation
 * Signature: (ILcom/wiyun/engine/afcanim/AFCClipMapping;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_playAnimation__ILcom_wiyun_engine_afcanim_AFCClipMapping_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    playAnimation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_playAnimation__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setFrameIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setFrameIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    tick
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_tick
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setIgnoreFrameOffset
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setIgnoreFrameOffset
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isIgnoreFrameOffset
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isIgnoreFrameOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetFrameOffset
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetFrameOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setAFCSpriteCallback
 * Signature: (Lcom/wiyun/engine/afcanim/AFCSprite/IAFCSpriteCallback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setAFCSpriteCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getCurrentAnimationIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getCurrentAnimationIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getCurrentFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getCurrentFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getFrameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getFrameCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isReverse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isReverse
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setReverse
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setReverse
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getLoopCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getLoopCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setLoopCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setLoopCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isAnimationEnded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isAnimationEnded
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isFlipX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isFlipX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setFlipX
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setFlipX
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isFlipY
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isFlipY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setFlipY
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setFlipY
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setPaused
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setPaused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isPaused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isPaused
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetCurrentAnimationData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetCurrentAnimationData
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getUnitInterval
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getUnitInterval
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setUnitInterval
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setUnitInterval
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    isForceTickMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_isForceTickMode
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setForceTickMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setForceTickMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    getCollisionRectCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_getCollisionRectCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetCollisionRect
 * Signature: (ILcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetCollisionRect
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetCollisionRectRelativeToParent
 * Signature: (ILcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetCollisionRectRelativeToParent
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetCollisionRectRelativeToWorld
 * Signature: (ILcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetCollisionRectRelativeToWorld
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetFrameRect
 * Signature: (Lcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetFrameRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetFrameRectRelativeToParent
 * Signature: (Lcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetFrameRectRelativeToParent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetFrameRectRelativeToWorld
 * Signature: (Lcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetFrameRectRelativeToWorld
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setDebugDrawFrameRect
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setDebugDrawFrameRect
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    setDebugDrawCollisionRect
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_setDebugDrawCollisionRect
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    addClipMapping
 * Signature: (Lcom/wiyun/engine/afcanim/AFCClipMapping;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_addClipMapping
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    removeClipMappingByTag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_removeClipMappingByTag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    nativeGetClipMappingByTag
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_nativeGetClipMappingByTag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCSprite
 * Method:    replaceTextures
 * Signature: ([Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCSprite_replaceTextures
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
