/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_AFCClip */

#ifndef _Included_com_wiyun_engine_afcanim_AFCClip
#define _Included_com_wiyun_engine_afcanim_AFCClip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetClipPos
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetClipPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getImageIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getImageIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetImageRect
 * Signature: (Lcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetImageRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    isImageFlipX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_afcanim_AFCClip_isImageFlipX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getImageRotation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getImageRotation
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getEllipseColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getEllipseColor
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetEllipseSize
 * Signature: (Lcom/wiyun/engine/types/WYSize;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetEllipseSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getEllipseStartAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getEllipseStartAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getEllipseEndAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getEllipseEndAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getLineColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getLineColor
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetLineEndPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetLineEndPoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getRectangleColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getRectangleColor
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetRectangleSize
 * Signature: (Lcom/wiyun/engine/types/WYSize;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetRectangleSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getRoundRectColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getRoundRectColor
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetRoundRectSize
 * Signature: (Lcom/wiyun/engine/types/WYSize;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetRoundRectSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getRoundRectArcWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getRoundRectArcWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    getRoundRectArcHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_afcanim_AFCClip_getRoundRectArcHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetCollisionRectSize
 * Signature: (Lcom/wiyun/engine/types/WYSize;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetCollisionRectSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetTrianglePoint2
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetTrianglePoint2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClip
 * Method:    nativeGetTrianglePoint3
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClip_nativeGetTrianglePoint3
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
