/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_MWSprite */

#ifndef _Included_com_wiyun_engine_afcanim_MWSprite
#define _Included_com_wiyun_engine_afcanim_MWSprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_MWSprite
 * Method:    nativeInit
 * Signature: (II[Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_MWSprite_nativeInit__II_3Lcom_wiyun_engine_opengl_Texture2D_2
  (JNIEnv *, jobject, jint, jint, jobjectArray);

/*
 * Class:     com_wiyun_engine_afcanim_MWSprite
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;ZI[Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_MWSprite_nativeInit__Ljava_lang_String_2ZI_3Lcom_wiyun_engine_opengl_Texture2D_2
  (JNIEnv *, jobject, jstring, jboolean, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
