/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_AFCClipMapping */

#ifndef _Included_com_wiyun_engine_afcanim_AFCClipMapping
#define _Included_com_wiyun_engine_afcanim_AFCClipMapping
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    nativeInit
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_nativeInit__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    nativeInit
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_nativeInit__ILjava_lang_String_2Z
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_nativeInit__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_nativeInit__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    mapClip
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_mapClip__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    mapClip
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_mapClip__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    mapClip
 * Signature: (ILcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYRect;ZF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_mapClip__ILcom_wiyun_engine_opengl_Texture2D_2Lcom_wiyun_engine_types_WYPoint_2Lcom_wiyun_engine_types_WYRect_2ZF
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jboolean, jfloat);

/*
 * Class:     com_wiyun_engine_afcanim_AFCClipMapping
 * Method:    getTag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCClipMapping_getTag
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
