/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_afcanim_AFCAnimation */

#ifndef _Included_com_wiyun_engine_afcanim_AFCAnimation
#define _Included_com_wiyun_engine_afcanim_AFCAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_afcanim_AFCAnimation
 * Method:    getFrameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCAnimation_getFrameCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_afcanim_AFCAnimation
 * Method:    nativeGetFrameAt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_afcanim_AFCAnimation_nativeGetFrameAt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
