/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_dialog_DialogPopupTransition */

#ifndef _Included_com_wiyun_engine_dialog_DialogPopupTransition
#define _Included_com_wiyun_engine_dialog_DialogPopupTransition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_dialog_DialogPopupTransition
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_DialogPopupTransition_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
