/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_dialog_Dialog */

#ifndef _Included_com_wiyun_engine_dialog_Dialog
#define _Included_com_wiyun_engine_dialog_Dialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeShow
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeShow
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    dismiss
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_dismiss
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeSetBackground
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeSetBackground
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    getBackground
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_dialog_Dialog_getBackground
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeSetBackgroundPadding
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeSetBackgroundPadding
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeSetTitle
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeSetTitle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeSetContent
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeSetContent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeAddButton
 * Signature: (Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/utils/TargetSelector;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeAddButton
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeAddTwoColumnsButton
 * Signature: (Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/utils/TargetSelector;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/utils/TargetSelector;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeAddTwoColumnsButton
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeSetTransition
 * Signature: (Lcom/wiyun/engine/dialog/DialogTransition;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeSetTransition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_dialog_Dialog
 * Method:    nativeSetBackKeyEquivalentButtonIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_dialog_Dialog_nativeSetBackKeyEquivalentButtonIndex
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
