#if ANDROID

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_TextBox */

#ifndef _Included_com_wiyun_engine_nodes_TextBox
#define _Included_com_wiyun_engine_nodes_TextBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TextBox_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TextBox_setText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_nodes_TextBox_getText
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_nodes_TextBox_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_nodes_TextBox_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    getPositiveButton
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_nodes_TextBox_getPositiveButton
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    getNegativeButton
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_nodes_TextBox_getNegativeButton
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    isPassword
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_TextBox_isPassword
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    onOKButtonClicked
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TextBox_onOKButtonClicked
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    onCancelButtonClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TextBox_onCancelButtonClicked
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TextBox
 * Method:    onTextChanged
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TextBox_onTextChanged
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

#endif // #if ANDROID
