#if ANDROID

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_events_EventDispatcher */

#ifndef _Included_com_wiyun_engine_events_EventDispatcher
#define _Included_com_wiyun_engine_events_EventDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    nativeGetInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_events_EventDispatcher_nativeGetInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_events_EventDispatcher_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    keyDown
 * Signature: (Landroid/view/KeyEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_keyDown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    keyUp
 * Signature: (Landroid/view/KeyEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_keyUp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    keyMultiple
 * Signature: (Landroid/view/KeyEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_keyMultiple
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    touchesBegan
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_touchesBegan
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    touchesMoved
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_touchesMoved
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    touchesEnded
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_touchesEnded
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    touchesPointerBegan
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_touchesPointerBegan
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    touchesPointerEnded
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_touchesPointerEnded
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    touchesCancelled
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_touchesCancelled
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onDoubleTap
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onDoubleTap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onDoubleTapEvent
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onDoubleTapEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onSingleTapConfirmed
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onSingleTapConfirmed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onDown
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onDown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onFling
 * Signature: (Landroid/view/MotionEvent;Landroid/view/MotionEvent;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onFling
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onLongPress
 * Signature: (Landroid/view/MotionEvent;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_events_EventDispatcher_onLongPress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onScroll
 * Signature: (Landroid/view/MotionEvent;Landroid/view/MotionEvent;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onScroll
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onShowPress
 * Signature: (Landroid/view/MotionEvent;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_events_EventDispatcher_onShowPress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_events_EventDispatcher
 * Method:    onSingleTapUp
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_events_EventDispatcher_onSingleTapUp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif

#endif // #if ANDROID
