/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_BladeRibbon */

#ifndef _Included_com_wiyun_engine_nodes_BladeRibbon
#define _Included_com_wiyun_engine_nodes_BladeRibbon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/types/WYColor4B;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    setMaxPointCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_setMaxPointCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    getMaxPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_getMaxPointCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    nativeGetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_nativeGetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    setTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_setTexture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_BladeRibbon
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_BladeRibbon_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
