/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_SpriteBatchNode */

#ifndef _Included_com_wiyun_engine_nodes_SpriteBatchNode
#define _Included_com_wiyun_engine_nodes_SpriteBatchNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativesetTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativesetTexture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativegetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativegetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativegetTexAtlas
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativegetTexAtlas
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    isDither
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_isDither
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    setDither
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_setDither
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    isBlend
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_isBlend
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    setBlend
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_setBlend
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    setAlphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_setAlphaFunc
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    getBlendFuncSrc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_getBlendFuncSrc
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    getBlendFuncDst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_getBlendFuncDst
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    setBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_setBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
