/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Animation */

#ifndef _Included_com_wiyun_engine_nodes_Animation
#define _Included_com_wiyun_engine_nodes_Animation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Animation_nativeInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    getFrameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Animation_getFrameCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    nativeGetFrames
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Animation_nativeGetFrames
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    addFrame
 * Signature: (FLcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Animation_addFrame__FLcom_wiyun_engine_opengl_Texture2D_2
  (JNIEnv *, jobject, jfloat, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    addFrame
 * Signature: (FLcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Animation_addFrame__FLcom_wiyun_engine_types_WYRect_2
  (JNIEnv *, jobject, jfloat, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    addFrame
 * Signature: (Lcom/wiyun/engine/nodes/Frame;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Animation_addFrame__Lcom_wiyun_engine_nodes_Frame_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    getDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Animation_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Animation_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Animation
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/nodes/Animation/IAnimationCallback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Animation_setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
