/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Menu */

#ifndef _Included_com_wiyun_engine_nodes_Menu
#define _Included_com_wiyun_engine_nodes_Menu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    nativeInit
 * Signature: ([Lcom/wiyun/engine/nodes/MenuItem;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_nativeInit
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsVertically
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsVertically__
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsVertically
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsVertically__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsHorizontally
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsHorizontally__
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsHorizontally
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsHorizontally__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsInColumns
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsInColumns___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsInColumns
 * Signature: ([IF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsInColumns___3IF
  (JNIEnv *, jobject, jintArray, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsInRows
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsInRows___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_wiyun_engine_nodes_Menu
 * Method:    alignItemsInRows
 * Signature: ([IF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Menu_alignItemsInRows___3IF
  (JNIEnv *, jobject, jintArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
