/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_SpriteEx */

#ifndef _Included_com_wiyun_engine_nodes_SpriteEx
#define _Included_com_wiyun_engine_nodes_SpriteEx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_SpriteEx
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteEx_nativeInit__Lcom_wiyun_engine_opengl_Texture2D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteEx
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/types/WYRect;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteEx_nativeInit__Lcom_wiyun_engine_opengl_Texture2D_2Lcom_wiyun_engine_types_WYRect_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpriteEx
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/nodes/SpriteBatchNode;Lcom/wiyun/engine/types/WYRect;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteEx_nativeInit__Lcom_wiyun_engine_nodes_SpriteBatchNode_2Lcom_wiyun_engine_types_WYRect_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
