/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_AtlasLabel */

#ifndef _Included_com_wiyun_engine_nodes_AtlasLabel
#define _Included_com_wiyun_engine_nodes_AtlasLabel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_AtlasLabel_LEFT
#define com_wiyun_engine_nodes_AtlasLabel_LEFT 0L
#undef com_wiyun_engine_nodes_AtlasLabel_CENTER
#define com_wiyun_engine_nodes_AtlasLabel_CENTER 1L
#undef com_wiyun_engine_nodes_AtlasLabel_RIGHT
#define com_wiyun_engine_nodes_AtlasLabel_RIGHT 2L
/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Lcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/nodes/CharMap;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_nativeInit
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getBlendFuncSrc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getBlendFuncSrc
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getBlendFuncDst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getBlendFuncDst
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    nativeGetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_nativeGetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setTexture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getText
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setAlignment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setAlignment
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getAlignment
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    getLineSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_getLineSpacing
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_AtlasLabel
 * Method:    setLineSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_AtlasLabel_setLineSpacing
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
