/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_TGATileMapAtlas */

#ifndef _Included_com_wiyun_engine_nodes_TGATileMapAtlas
#define _Included_com_wiyun_engine_nodes_TGATileMapAtlas
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_TGATileMapAtlas_INVALID_TAG
#define com_wiyun_engine_nodes_TGATileMapAtlas_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_nodes_TGATileMapAtlas
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TGATileMapAtlas_nativeInit
  (JNIEnv *, jobject, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
