/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_VirtualJoystick */

#ifndef _Included_com_wiyun_engine_nodes_VirtualJoystick
#define _Included_com_wiyun_engine_nodes_VirtualJoystick
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_CENTER
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_CENTER -1L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_NORTH
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_NORTH -2L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_SOUTH
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_SOUTH -3L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_EAST
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_EAST -4L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_WEST
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_WEST -5L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_NORTH_EAST
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_NORTH_EAST -6L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_NORTH_WEST
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_NORTH_WEST -7L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_SOUTH_EAST
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_SOUTH_EAST -8L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJD_SOUTH_WEST
#define com_wiyun_engine_nodes_VirtualJoystick_VJD_SOUTH_WEST -9L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJS_FIVE_DIRECTIONS
#define com_wiyun_engine_nodes_VirtualJoystick_VJS_FIVE_DIRECTIONS 0L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJS_NINE_DIRECTIONS
#define com_wiyun_engine_nodes_VirtualJoystick_VJS_NINE_DIRECTIONS 1L
#undef com_wiyun_engine_nodes_VirtualJoystick_VJS_FULL_DIRECTIONS
#define com_wiyun_engine_nodes_VirtualJoystick_VJS_FULL_DIRECTIONS 2L
/*
 * Class:     com_wiyun_engine_nodes_VirtualJoystick
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_VirtualJoystick_nativeInit
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_VirtualJoystick
 * Method:    getEventStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_VirtualJoystick_getEventStyle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_VirtualJoystick
 * Method:    setEventStyle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_VirtualJoystick_setEventStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_VirtualJoystick
 * Method:    setAutoReset
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_VirtualJoystick_setAutoReset
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_VirtualJoystick
 * Method:    isAutoReset
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_VirtualJoystick_isAutoReset
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_VirtualJoystick
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/nodes/VirtualJoystick/IVirtualJoystickCallback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_VirtualJoystick_setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
