/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Layer */

#ifndef _Included_com_wiyun_engine_nodes_Layer
#define _Included_com_wiyun_engine_nodes_Layer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_Layer_INVALID_TAG
#define com_wiyun_engine_nodes_Layer_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_nodes_Layer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Layer_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
