/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_ActionManager */

#ifndef _Included_com_wiyun_engine_nodes_ActionManager
#define _Included_com_wiyun_engine_nodes_ActionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    nativeGetInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_ActionManager_nativeGetInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    pauseAllActions
 * Signature: (Lcom/wiyun/engine/nodes/Node;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_pauseAllActions
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    resumeAllActions
 * Signature: (Lcom/wiyun/engine/nodes/Node;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_resumeAllActions
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    addAction
 * Signature: (Lcom/wiyun/engine/actions/Action;Lcom/wiyun/engine/nodes/Node;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_addAction
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    removeAllActions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_removeAllActions__
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    removeAllActions
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_removeAllActions__Lcom_wiyun_engine_nodes_Node_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    removeAllActions
 * Signature: (Lcom/wiyun/engine/nodes/Node;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_removeAllActions__Lcom_wiyun_engine_nodes_Node_2Z
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    removeAction
 * Signature: (Lcom/wiyun/engine/actions/Action;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_removeAction__Lcom_wiyun_engine_actions_Action_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    removeAction
 * Signature: (Lcom/wiyun/engine/nodes/Node;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ActionManager_removeAction__Lcom_wiyun_engine_nodes_Node_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_ActionManager
 * Method:    getRunningActionCount
 * Signature: (Lcom/wiyun/engine/nodes/Node;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_ActionManager_getRunningActionCount
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
