/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_MenuItem */

#ifndef _Included_com_wiyun_engine_nodes_MenuItem
#define _Included_com_wiyun_engine_nodes_MenuItem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_MenuItem_DEFAULT_FONT_SIZE
#define com_wiyun_engine_nodes_MenuItem_DEFAULT_FONT_SIZE 32L
/*
 * Class:     com_wiyun_engine_nodes_MenuItem
 * Method:    getClickScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_MenuItem_getClickScale
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MenuItem
 * Method:    setClickScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItem_setClickScale
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
