/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_ScrollableLayer */

#ifndef _Included_com_wiyun_engine_nodes_ScrollableLayer
#define _Included_com_wiyun_engine_nodes_ScrollableLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/types/WYColor4B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setVertical
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setVertical
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    isVertical
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_isVertical
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setHorizontal
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setHorizontal
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    isHorizontal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_isHorizontal
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    addScrollableChild
 * Signature: (Lcom/wiyun/engine/nodes/Node;II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_addScrollableChild
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    removeScrollableChild
 * Signature: (Lcom/wiyun/engine/nodes/Node;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_removeScrollableChild
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    removeScrollableChildByTag
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_removeScrollableChildByTag
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    removeAllScrollableChildrenLocked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_removeAllScrollableChildrenLocked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getScrollableChildByTag
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getScrollableChildByTag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    nativeGetScrollExtent
 * Signature: (Lcom/wiyun/engine/types/WYSize;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_nativeGetScrollExtent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setHorizontalThumb
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setHorizontalThumb
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setVerticalThumb
 * Signature: (Lcom/wiyun/engine/nodes/Node;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setVerticalThumb
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setThumbFadeOutTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setThumbFadeOutTime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getThumbFadeOutTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getThumbFadeOutTime
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setRightMargin
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setRightMargin
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setLeftMargin
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setLeftMargin
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getLeftMargin
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getLeftMargin
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getRightMargin
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getRightMargin
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setTopMargin
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setTopMargin
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getTopMargin
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getTopMargin
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setBottomMargin
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setBottomMargin
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getBottomMargin
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getBottomMargin
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getOffsetX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getOffsetX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    getOffsetY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_getOffsetY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setOffsetX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setOffsetX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setOffsetY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setOffsetY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    isAtXEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_isAtXEnd
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    isAtYEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_isAtYEnd
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_ScrollableLayer
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/nodes/ScrollableLayer/IScrollableLayerCallback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ScrollableLayer_setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
