/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_RenderTexture */

#ifndef _Included_com_wiyun_engine_nodes_RenderTexture
#define _Included_com_wiyun_engine_nodes_RenderTexture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_nativeInit__
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_nativeInit__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    beginRender
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_beginRender__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    beginRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_beginRender__
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    endRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_endRender
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    clear
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_clear
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    getBlendFuncSrc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_RenderTexture_getBlendFuncSrc
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    getBlendFuncDst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_RenderTexture_getBlendFuncDst
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    nativeSetBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_nativeSetBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_RenderTexture_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_RenderTexture_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_RenderTexture
 * Method:    nativeCreateTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_RenderTexture_nativeCreateTexture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
