/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Cover */

#ifndef _Included_com_wiyun_engine_nodes_Cover
#define _Included_com_wiyun_engine_nodes_Cover
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setPosition
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setPosition
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    getPosistionX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Cover_getPositionX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    getPosistionY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Cover_getPositionY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    getPosistionZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Cover_getPositionZ
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setRotateY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setRotateY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    getRotateY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Cover_getRotateY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    getScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Cover_getScale
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    nativeGetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Cover_nativeGetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setTexture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    nativeGetNext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Cover_nativeGetNext
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setNext
 * Signature: (Lcom/wiyun/engine/nodes/Cover;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setNext
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    nativeGetPrev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Cover_nativeGetPrev
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setPrev
 * Signature: (Lcom/wiyun/engine/nodes/Cover;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setPrev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    getAutoUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_Cover_getAutoUpdate
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Cover
 * Method:    setAutoUpdate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Cover_setAutoUpdate
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
