/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_SpriteBatchNode */

#ifndef _Included_com_wiyun_engine_nodes_SpriteBatchNode
#define _Included_com_wiyun_engine_nodes_SpriteBatchNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_SpriteBatchNode
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpriteBatchNode_nativeInit
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
