/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Slider */

#ifndef _Included_com_wiyun_engine_nodes_Slider
#define _Included_com_wiyun_engine_nodes_Slider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/nodes/Sprite;Lcom/wiyun/engine/nodes/Sprite;Lcom/wiyun/engine/nodes/Sprite;Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Slider_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    getMin
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Slider_getMin
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    setMin
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Slider_setMin
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    getMax
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Slider_getMax
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    setMax
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Slider_setMax
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    getValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Slider_getValue
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    setValue
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Slider_setValue
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    isShowFullBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_Slider_isShowFullBar
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    setShowFullBar
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Slider_setShowFullBar
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    isVertical
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_Slider_isVertical
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Slider
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/nodes/Slider/ISliderCallback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Slider_setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
