/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_MenuItemAtlasLabel */

#ifndef _Included_com_wiyun_engine_nodes_MenuItemAtlasLabel
#define _Included_com_wiyun_engine_nodes_MenuItemAtlasLabel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_MenuItemAtlasLabel_INVALID_TAG
#define com_wiyun_engine_nodes_MenuItemAtlasLabel_INVALID_TAG -1L
#undef com_wiyun_engine_nodes_MenuItemAtlasLabel_DEFAULT_FONT_SIZE
#define com_wiyun_engine_nodes_MenuItemAtlasLabel_DEFAULT_FONT_SIZE 32L
#undef com_wiyun_engine_nodes_MenuItemAtlasLabel_TAG_CURRENT_ITEM
#define com_wiyun_engine_nodes_MenuItemAtlasLabel_TAG_CURRENT_ITEM -1061138431L
#undef com_wiyun_engine_nodes_MenuItemAtlasLabel_TAG_ZOOM_ACTION
#define com_wiyun_engine_nodes_MenuItemAtlasLabel_TAG_ZOOM_ACTION -1061138430L
/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/utils/TargetSelector;Lcom/wiyun/engine/utils/TargetSelector;Lcom/wiyun/engine/nodes/AtlasLabel;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    getAlpha
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    setAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_setAlpha
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    nativeGetColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_nativeGetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    nativeSetColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_nativeSetColor
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    nativeGetDisabledColor
 * Signature: (Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_nativeGetDisabledColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MenuItemAtlasLabel
 * Method:    nativeSetDisabledColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MenuItemAtlasLabel_nativeSetDisabledColor
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
