/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Timer */

#ifndef _Included_com_wiyun_engine_nodes_Timer
#define _Included_com_wiyun_engine_nodes_Timer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/utils/TargetSelector;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_nativeInit__Lcom_wiyun_engine_utils_TargetSelector_2F
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/utils/TargetSelector;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_nativeInit__Lcom_wiyun_engine_utils_TargetSelector_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    setInterval
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_setInterval
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    getInterval
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Timer_getInterval
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    setFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_setFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    getFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Timer_getFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    setOneShot
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_setOneShot
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    isOneShot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_Timer_isOneShot
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    setMaxInvocation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_setMaxInvocation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    getMaxInvocation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Timer_getMaxInvocation
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    getCurrentInvocationCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Timer_getCurrentInvocationCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Timer
 * Method:    fire
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Timer_fire
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
