/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_TileMapAtlas */

#ifndef _Included_com_wiyun_engine_nodes_TileMapAtlas
#define _Included_com_wiyun_engine_nodes_TileMapAtlas
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_TileMapAtlas_INVALID_TAG
#define com_wiyun_engine_nodes_TileMapAtlas_INVALID_TAG -1L

/*
 * Class:     com_wiyun_engine_nodes_TileMapAtlas
 * Method:    hasTileAt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_TileMapAtlas_hasTileAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_TileMapAtlas
 * Method:    getHorizontalTileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_TileMapAtlas_getHorizontalTileCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TileMapAtlas
 * Method:    getVerticalTileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_TileMapAtlas_getVerticalTileCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_TileMapAtlas
 * Method:    tileValueAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_TileMapAtlas_tileValueAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_TileMapAtlas
 * Method:    getTile
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_TileMapAtlas_getTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_TileMapAtlas
 * Method:    setTile
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_TileMapAtlas_setTile
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
