/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_StripRibbon */

#ifndef _Included_com_wiyun_engine_nodes_StripRibbon
#define _Included_com_wiyun_engine_nodes_StripRibbon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_StripRibbon
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/types/WYColor4B;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_StripRibbon_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
