/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_MotionStreak */

#ifndef _Included_com_wiyun_engine_nodes_MotionStreak
#define _Included_com_wiyun_engine_nodes_MotionStreak
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_MotionStreak_STYLE_STRIP
#define com_wiyun_engine_nodes_MotionStreak_STYLE_STRIP 0L
#undef com_wiyun_engine_nodes_MotionStreak_STYLE_SPOT
#define com_wiyun_engine_nodes_MotionStreak_STYLE_SPOT 1L
#undef com_wiyun_engine_nodes_MotionStreak_STYLE_BLADE
#define com_wiyun_engine_nodes_MotionStreak_STYLE_BLADE 2L
/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    getRibbon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_MotionStreak_getRibbon
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    nativeInit
 * Signature: (FLcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/types/WYColor4B;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_nativeInit
  (JNIEnv *, jobject, jfloat, jobject, jobject, jint);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    nativeGetLastLocation
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_nativeGetLastLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    nativeGetCurrentLocation
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_nativeGetCurrentLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    nativeGetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_MotionStreak_nativeGetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    setTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_setTexture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    getBlendFuncSrc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_MotionStreak_getBlendFuncSrc
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    getBlendFuncDst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_MotionStreak_getBlendFuncDst
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    setBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_setBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    setPaused
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_setPaused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    isPaused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_nodes_MotionStreak_isPaused
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    addPoint
 * Signature: (FFZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_addPoint
  (JNIEnv *, jobject, jfloat, jfloat, jboolean);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    getStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_MotionStreak_getStyle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    setSegmentThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_MotionStreak_setSegmentThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_MotionStreak
 * Method:    getSegmentThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_MotionStreak_getSegmentThreshold
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
