/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_SpotRibbon */

#ifndef _Included_com_wiyun_engine_nodes_SpotRibbon
#define _Included_com_wiyun_engine_nodes_SpotRibbon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_SpotRibbon
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;Lcom/wiyun/engine/types/WYColor4B;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpotRibbon_nativeInit
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_SpotRibbon
 * Method:    setDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpotRibbon_setDistance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_SpotRibbon
 * Method:    getDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_SpotRibbon_getDistance
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpotRibbon
 * Method:    nativeGetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_SpotRibbon_nativeGetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_SpotRibbon
 * Method:    setTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_SpotRibbon_setTexture
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
