/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_ArrayTileMapAtlas */

#ifndef _Included_com_wiyun_engine_nodes_ArrayTileMapAtlas
#define _Included_com_wiyun_engine_nodes_ArrayTileMapAtlas
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_nodes_ArrayTileMapAtlas_INVALID_TAG
#define com_wiyun_engine_nodes_ArrayTileMapAtlas_INVALID_TAG -1L
/*
 * Class:     com_wiyun_engine_nodes_ArrayTileMapAtlas
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;IIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ArrayTileMapAtlas_nativeInit
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_nodes_ArrayTileMapAtlas
 * Method:    setTiles
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_ArrayTileMapAtlas_setTiles
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
