/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_nodes_Scheduler */

#ifndef _Included_com_wiyun_engine_nodes_Scheduler
#define _Included_com_wiyun_engine_nodes_Scheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_nodes_Scheduler
 * Method:    getTimeScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_nodes_Scheduler_getTimeScale
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Scheduler
 * Method:    setTimeScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Scheduler_setTimeScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_nodes_Scheduler
 * Method:    nativeGetInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_nodes_Scheduler_nativeGetInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_nodes_Scheduler
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Scheduler_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Scheduler
 * Method:    schedule
 * Signature: (Lcom/wiyun/engine/nodes/Scheduler/Timer;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Scheduler_schedule
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_nodes_Scheduler
 * Method:    unschedule
 * Signature: (Lcom/wiyun/engine/nodes/Scheduler/Timer;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_nodes_Scheduler_unschedule
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
