/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ease_EaseBounceOut */

#ifndef _Included_com_wiyun_engine_actions_ease_EaseBounceOut
#define _Included_com_wiyun_engine_actions_ease_EaseBounceOut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_ease_EaseBounceOut
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/actions/IntervalAction;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ease_EaseBounceOut_nativeInit
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
