/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ease_EaseAction */

#ifndef _Included_com_wiyun_engine_actions_ease_EaseAction
#define _Included_com_wiyun_engine_actions_ease_EaseAction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_ease_EaseAction
 * Method:    setWrappedAction
 * Signature: (Lcom/wiyun/engine/actions/IntervalAction;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ease_EaseAction_setWrappedAction
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
