/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_ease_EaseElasticOut */

#ifndef _Included_com_wiyun_engine_actions_ease_EaseElasticOut
#define _Included_com_wiyun_engine_actions_ease_EaseElasticOut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_ease_EaseElasticOut
 * Method:    nativeInit
 * Signature: (Lcom/wiyun/engine/actions/IntervalAction;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_ease_EaseElasticOut_nativeInit
  (JNIEnv *, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
