/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_particle_ParticleSystem */

#ifndef _Included_com_wiyun_engine_particle_ParticleSystem
#define _Included_com_wiyun_engine_particle_ParticleSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_particle_ParticleSystem_INVALID_TAG
#define com_wiyun_engine_particle_ParticleSystem_INVALID_TAG -1L
#undef com_wiyun_engine_particle_ParticleSystem_PARTICLE_DURATION_INFINITY
#define com_wiyun_engine_particle_ParticleSystem_PARTICLE_DURATION_INFINITY -1L
#undef com_wiyun_engine_particle_ParticleSystem_PARTICLE_START_SIZE_EQUAL_TO_END_SIZE
#define com_wiyun_engine_particle_ParticleSystem_PARTICLE_START_SIZE_EQUAL_TO_END_SIZE -1L
#undef com_wiyun_engine_particle_ParticleSystem_PARTICLE_START_RADIUS_EQUAL_TO_END_RADIUS
#define com_wiyun_engine_particle_ParticleSystem_PARTICLE_START_RADIUS_EQUAL_TO_END_RADIUS -1L
#undef com_wiyun_engine_particle_ParticleSystem_GRAVITY
#define com_wiyun_engine_particle_ParticleSystem_GRAVITY 1L
#undef com_wiyun_engine_particle_ParticleSystem_RADIUS
#define com_wiyun_engine_particle_ParticleSystem_RADIUS 2L
#undef com_wiyun_engine_particle_ParticleSystem_FREE
#define com_wiyun_engine_particle_ParticleSystem_FREE 1L
#undef com_wiyun_engine_particle_ParticleSystem_GROUPED
#define com_wiyun_engine_particle_ParticleSystem_GROUPED 2L
/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getCenterOfGravityX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getCenterOfGravityX
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getCenterOfGravityY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getCenterOfGravityY
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setParticlePositionVariance
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setParticlePositionVariance
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setDirectionAngleVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setDirectionAngleVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setStartSizeVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setStartSizeVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setEndSizeVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setEndSizeVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setLifeVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setLifeVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setStartColorVariance
 * Signature: (FFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setStartColorVariance
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setEndColorVariance
 * Signature: (FFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setEndColorVariance
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setStartSpinVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setStartSpinVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setEndSpinVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setEndSpinVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setSpeedVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setSpeedVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setParticleGravity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setParticleGravity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setTangentialAccelerationVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setTangentialAccelerationVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setRadialAccelerationVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setRadialAccelerationVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setStartRadiusVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setStartRadiusVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setEndRadiusVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setEndRadiusVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setRotationVariance
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setRotationVariance
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getParticleCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getParticleCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getMaxParticleCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getMaxParticleCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    stopSystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_stopSystem
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    resetSystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_resetSystem
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    nativeGetTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_nativeGetTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setTexture
 * Signature: (Lcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setTexture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getBlendFuncSrc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getBlendFuncSrc
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getBlendFuncDst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getBlendFuncDst
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setBlendAdditive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setBlendAdditive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    isBlendAdditive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_particle_ParticleSystem_isBlendAdditive
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getPositionType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getPositionType
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setPositionType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setPositionType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getEmitterMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getEmitterMode
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setEmitterMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setEmitterMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getEmissionRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getEmissionRate
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setEmissionRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setEmissionRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    isAutoRemoveOnFinish
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_particle_ParticleSystem_isAutoRemoveOnFinish
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    setAutoRemoveOnFinish
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_ParticleSystem_setAutoRemoveOnFinish
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_particle_ParticleSystem
 * Method:    getLife
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_particle_ParticleSystem_getLife
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
