/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_particle_PointParticleSystem */

#ifndef _Included_com_wiyun_engine_particle_PointParticleSystem
#define _Included_com_wiyun_engine_particle_PointParticleSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_particle_PointParticleSystem_INVALID_TAG
#define com_wiyun_engine_particle_PointParticleSystem_INVALID_TAG -1L
#undef com_wiyun_engine_particle_PointParticleSystem_PARTICLE_DURATION_INFINITY
#define com_wiyun_engine_particle_PointParticleSystem_PARTICLE_DURATION_INFINITY -1L
#undef com_wiyun_engine_particle_PointParticleSystem_PARTICLE_START_SIZE_EQUAL_TO_END_SIZE
#define com_wiyun_engine_particle_PointParticleSystem_PARTICLE_START_SIZE_EQUAL_TO_END_SIZE -1L
#undef com_wiyun_engine_particle_PointParticleSystem_PARTICLE_START_RADIUS_EQUAL_TO_END_RADIUS
#define com_wiyun_engine_particle_PointParticleSystem_PARTICLE_START_RADIUS_EQUAL_TO_END_RADIUS -1L
#undef com_wiyun_engine_particle_PointParticleSystem_GRAVITY
#define com_wiyun_engine_particle_PointParticleSystem_GRAVITY 1L
#undef com_wiyun_engine_particle_PointParticleSystem_RADIUS
#define com_wiyun_engine_particle_PointParticleSystem_RADIUS 2L
#undef com_wiyun_engine_particle_PointParticleSystem_FREE
#define com_wiyun_engine_particle_PointParticleSystem_FREE 1L
#undef com_wiyun_engine_particle_PointParticleSystem_GROUPED
#define com_wiyun_engine_particle_PointParticleSystem_GROUPED 2L
/*
 * Class:     com_wiyun_engine_particle_PointParticleSystem
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_particle_PointParticleSystem_nativeInit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
