/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_particle_HGEParticleLoader */

#ifndef _Included_com_wiyun_engine_particle_HGEParticleLoader
#define _Included_com_wiyun_engine_particle_HGEParticleLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_particle_HGEParticleLoader
 * Method:    nativeLoad
 * Signature: (IILcom/wiyun/engine/opengl/Texture2D;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_HGEParticleLoader_nativeLoad__IILcom_wiyun_engine_opengl_Texture2D_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_wiyun_engine_particle_HGEParticleLoader
 * Method:    nativeLoad
 * Signature: (Ljava/lang/String;ILcom/wiyun/engine/opengl/Texture2D;ZF)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_particle_HGEParticleLoader_nativeLoad__Ljava_lang_String_2ILcom_wiyun_engine_opengl_Texture2D_2ZF
  (JNIEnv *, jclass, jstring, jint, jobject, jboolean, jfloat);

#ifdef __cplusplus
}
#endif
#endif
