/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_GridAction */

#ifndef _Included_com_wiyun_engine_actions_grid_GridAction
#define _Included_com_wiyun_engine_actions_grid_GridAction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    getAmplitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_actions_grid_GridAction_getAmplitude
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    setAmplitude
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_GridAction_setAmplitude
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    getAmplitudeRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_actions_grid_GridAction_getAmplitudeRate
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    setAmplitudeRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_GridAction_setAmplitudeRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    getGridWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_grid_GridAction_getGridWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    getGridHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_grid_GridAction_getGridHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    makeGrid
 * Signature: ()Lcom/wiyun/engine/grid/BaseGrid;
 */
JNIEXPORT jobject JNICALL Java_com_wiyun_engine_actions_grid_GridAction_makeGrid
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_GridAction
 * Method:    getGridClass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_actions_grid_GridAction_getGridClass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
