/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_Shaky3D */

#ifndef _Included_com_wiyun_engine_actions_grid_Shaky3D
#define _Included_com_wiyun_engine_actions_grid_Shaky3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_Shaky3D
 * Method:    nativeInit
 * Signature: (FIIIIZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_Shaky3D_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
