/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_GridFlipY */

#ifndef _Included_com_wiyun_engine_actions_grid_GridFlipY
#define _Included_com_wiyun_engine_actions_grid_GridFlipY
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_GridFlipY
 * Method:    nativeInit
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_GridFlipY_nativeInit
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
