/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_Suck */

#ifndef _Included_com_wiyun_engine_actions_grid_Suck
#define _Included_com_wiyun_engine_actions_grid_Suck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_Suck
 * Method:    nativeInit
 * Signature: (FIIFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_Suck_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
