/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_TiledGrid3DAction */

#ifndef _Included_com_wiyun_engine_actions_grid_TiledGrid3DAction
#define _Included_com_wiyun_engine_actions_grid_TiledGrid3DAction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_TiledGrid3DAction
 * Method:    getTile
 * Signature: (IILcom/wiyun/engine/types/WYQuad3D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_TiledGrid3DAction_getTile
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_TiledGrid3DAction
 * Method:    getOriginalTile
 * Signature: (IILcom/wiyun/engine/types/WYQuad3D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_TiledGrid3DAction_getOriginalTile
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_wiyun_engine_actions_grid_TiledGrid3DAction
 * Method:    setTile
 * Signature: (IIFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_TiledGrid3DAction_setTile
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
