/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_Liquid */

#ifndef _Included_com_wiyun_engine_actions_grid_Liquid
#define _Included_com_wiyun_engine_actions_grid_Liquid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_Liquid
 * Method:    nativeInit
 * Signature: (FIIFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_Liquid_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
