/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_ReuseGrid */

#ifndef _Included_com_wiyun_engine_actions_grid_ReuseGrid
#define _Included_com_wiyun_engine_actions_grid_ReuseGrid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_ReuseGrid
 * Method:    nativeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_ReuseGrid_nativeInit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
