/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_SplitRows */

#ifndef _Included_com_wiyun_engine_actions_grid_SplitRows
#define _Included_com_wiyun_engine_actions_grid_SplitRows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_SplitRows
 * Method:    nativeInit
 * Signature: (FII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_SplitRows_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
