/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_TopTilesShrinkOut */

#ifndef _Included_com_wiyun_engine_actions_grid_TopTilesShrinkOut
#define _Included_com_wiyun_engine_actions_grid_TopTilesShrinkOut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_TopTilesShrinkOut
 * Method:    nativeInit
 * Signature: (FII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_TopTilesShrinkOut_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
