/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_actions_grid_Twirl */

#ifndef _Included_com_wiyun_engine_actions_grid_Twirl
#define _Included_com_wiyun_engine_actions_grid_Twirl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_actions_grid_Twirl
 * Method:    nativeInit
 * Signature: (FIIFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_actions_grid_Twirl_nativeInit
  (JNIEnv *, jobject, jfloat, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
