/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_DebugDraw */

#ifndef _Included_com_wiyun_engine_box2d_DebugDraw
#define _Included_com_wiyun_engine_box2d_DebugDraw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawPolygon
 * Signature: ([Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawPolygon
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawSolidPolygon
 * Signature: ([Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawSolidPolygon
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawCircle
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FLcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawCircle
  (JNIEnv *, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawSolidCircle
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FLcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawSolidCircle
  (JNIEnv *, jobject, jobject, jfloat, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawSegment
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawSegment
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawTransform
 * Signature: (Lcom/wiyun/engine/box2d/common/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawTransform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_DebugDraw
 * Method:    drawPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FLcom/wiyun/engine/types/WYColor3B;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_DebugDraw_drawPoint
  (JNIEnv *, jobject, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
