/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_FixtureAnimation */

#ifndef _Included_com_wiyun_engine_box2d_FixtureAnimation
#define _Included_com_wiyun_engine_box2d_FixtureAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    nativeAddFrame
 * Signature: (FLcom/wiyun/engine/opengl/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_nativeAddFrame
  (JNIEnv *, jobject, jfloat, jobject);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    start
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/Fixture;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    isLoop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_isLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    setLoop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_setLoop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    getDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    setDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_setDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_FixtureAnimation
 * Method:    setCallback
 * Signature: (Lcom/wiyun/engine/box2d/FixtureAnimation/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_FixtureAnimation_setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
