/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_CollisionDetector */

#ifndef _Included_com_wiyun_engine_box2d_CollisionDetector
#define _Included_com_wiyun_engine_box2d_CollisionDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_CollisionDetector
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_CollisionDetector_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_CollisionDetector
 * Method:    isCollided
 * Signature: (Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/box2d/CDResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_CollisionDetector_isCollided__Lcom_wiyun_engine_nodes_Node_2Lcom_wiyun_engine_nodes_Node_2Lcom_wiyun_engine_box2d_CDResult_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_CollisionDetector
 * Method:    isCollided
 * Signature: (Lcom/wiyun/engine/nodes/Node;Lcom/wiyun/engine/types/WYRect;Lcom/wiyun/engine/box2d/CDResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_CollisionDetector_isCollided__Lcom_wiyun_engine_nodes_Node_2Lcom_wiyun_engine_types_WYRect_2Lcom_wiyun_engine_box2d_CDResult_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_CollisionDetector
 * Method:    isCollided
 * Signature: (Lcom/wiyun/engine/types/WYRect;Lcom/wiyun/engine/types/WYRect;Lcom/wiyun/engine/box2d/CDResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_CollisionDetector_isCollided__Lcom_wiyun_engine_types_WYRect_2Lcom_wiyun_engine_types_WYRect_2Lcom_wiyun_engine_box2d_CDResult_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_CollisionDetector
 * Method:    setNodeShape
 * Signature: (Lcom/wiyun/engine/nodes/Node;[Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_CollisionDetector_setNodeShape__Lcom_wiyun_engine_nodes_Node_2_3Lcom_wiyun_engine_types_WYPoint_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_wiyun_engine_box2d_CollisionDetector
 * Method:    setNodeShape
 * Signature: (Lcom/wiyun/engine/nodes/Node;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_CollisionDetector_setNodeShape__Lcom_wiyun_engine_nodes_Node_2I
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
