/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_Box2D */

#ifndef _Included_com_wiyun_engine_box2d_Box2D
#define _Included_com_wiyun_engine_box2d_Box2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_Box2D_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    nativeGetWorld
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_Box2D_nativeGetWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    isDebugDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_Box2D_isDebugDraw
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    setDebugDraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_Box2D_setDebugDraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    pixel2Meter
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_Box2D_pixel2Meter
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    meter2Pixel
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_Box2D_meter2Pixel
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    getMeterPixels
 * Signature: ()I
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_Box2D_getMeterPixels
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_Box2D
 * Method:    setMeterPixels
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_Box2D_setMeterPixels
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
