/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_ContactImpulse */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_ContactImpulse
#define _Included_com_wiyun_engine_box2d_dynamics_ContactImpulse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_ContactImpulse
 * Method:    getNormalImpulse
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_ContactImpulse_getNormalImpulse
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_ContactImpulse
 * Method:    getTangentImpulse
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_ContactImpulse_getTangentImpulse
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
