/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_World */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_World
#define _Included_com_wiyun_engine_box2d_dynamics_World
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setContactListener
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/World/IContactListener;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setContactListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setGravity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setGravity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    nativeCreateBody
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/BodyDef;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_nativeCreateBody
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    createController
 * Signature: (Lcom/wiyun/engine/box2d/controllers/ControllerDef;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_createController
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    destroyController
 * Signature: (Lcom/wiyun/engine/box2d/controllers/Controller;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_destroyController
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    createJoint
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/joints/JointDef;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_createJoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    step
 * Signature: (FII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_step
  (JNIEnv *, jobject, jfloat, jint, jint);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    clearForces
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_clearForces
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    queryAABB
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/World/IQueryCallback;FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_queryAABB
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    destroyJoint
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/joints/Joint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_destroyJoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    nativeGetFirstBody
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_nativeGetFirstBody
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    rayCast
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/World/IRayCastCallback;FFFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_rayCast
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    destroyBody
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/Body;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_destroyBody
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setDestructionListener
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/World/IDestructionListener;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setDestructionListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    nativeGetFirstJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_nativeGetFirstJoint
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    nativeGetFirstContact
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_nativeGetFirstContact
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setWarmStarting
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setWarmStarting
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getWarmStarting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getWarmStarting
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setContinuousPhysics
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setContinuousPhysics
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setSubStepping
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setSubStepping
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getSubStepping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getSubStepping
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getProxyCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getProxyCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getBodyCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getBodyCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getJointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getJointCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getContactCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getContactCount
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    nativeGetGravity
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_nativeGetGravity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    isLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_World_isLocked
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setAutoClearForces
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setAutoClearForces
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getAutoClearForces
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getAutoClearForces
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setNoSolidDraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setNoSolidDraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    setAllowSleeping
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_World_setAllowSleeping
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_World
 * Method:    getAllowSleeping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_World_getAllowSleeping
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
