/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_Body */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_Body
#define _Included_com_wiyun_engine_box2d_dynamics_Body
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_dynamics_Body_TYPE_STATIC
#define com_wiyun_engine_box2d_dynamics_Body_TYPE_STATIC 0L
#undef com_wiyun_engine_box2d_dynamics_Body_TYPE_KINEMATIC
#define com_wiyun_engine_box2d_dynamics_Body_TYPE_KINEMATIC 1L
#undef com_wiyun_engine_box2d_dynamics_Body_TYPE_DYNAMIC
#define com_wiyun_engine_box2d_dynamics_Body_TYPE_DYNAMIC 2L
/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeCreateFixture
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/FixtureDef;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeCreateFixture__Lcom_wiyun_engine_box2d_dynamics_FixtureDef_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeCreateFixture
 * Signature: (Lcom/wiyun/engine/box2d/collision/Shape;F)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeCreateFixture__Lcom_wiyun_engine_box2d_collision_Shape_2F
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getMass
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getMass
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setAwake
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setAwake
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getInertia
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getInertia
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    applyTorque
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_applyTorque
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    applyForce
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_applyForce
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    applyForceToCenter
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_applyForceToCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    applyLinearImpulse
 * Signature: (Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_applyLinearImpulse
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    applyAngularImpulse
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_applyAngularImpulse
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetWorldVector
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetWorldVector
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetWorldPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetWorldPoint
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setLinearVelocity
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setLinearVelocity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetLinearVelocity
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetLinearVelocity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetTransform
 * Signature: (Lcom/wiyun/engine/box2d/common/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetTransform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setAngularVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setAngularVelocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getAngularVelocity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getAngularVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetWorldCenter
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetWorldCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetLocalCenter
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetLocalCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    destroyFixture
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/Fixture;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_destroyFixture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetPosition
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setTransform
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setTransform
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    isAwake
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_isAwake
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetNext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetNext
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetLocalPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetLocalPoint
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getUserData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getUserData
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setUserData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetMassData
 * Signature: (Lcom/wiyun/engine/box2d/collision/MassData;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetMassData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setMassData
 * Signature: (Lcom/wiyun/engine/box2d/collision/MassData;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setMassData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    resetMassData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_resetMassData
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetLocalVector
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetLocalVector
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetLinearVelocityFromWorldPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetLinearVelocityFromWorldPoint
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetLinearVelocityFromLocalPoint
 * Signature: (Lcom/wiyun/engine/types/WYPoint;FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetLinearVelocityFromLocalPoint
  (JNIEnv *, jobject, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getLinearDamping
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getLinearDamping
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setLinearDamping
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setLinearDamping
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    getAngularDamping
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_getAngularDamping
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setAngularDamping
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setAngularDamping
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setBullet
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setBullet
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    isBullet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_isBullet
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setSleepingAllowed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setSleepingAllowed
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    isSleepingAllowed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_isSleepingAllowed
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    setFixedRotation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_setFixedRotation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    isFixedRotation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_isFixedRotation
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetFirstFixture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetFirstFixture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetFirstJointEdge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetFirstJointEdge
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetContactEdge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetContactEdge
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_Body
 * Method:    nativeGetWorld
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_Body_nativeGetWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
