/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_BodyDef */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_BodyDef
#define _Included_com_wiyun_engine_box2d_dynamics_BodyDef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setPosition
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setPosition__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setAngularDamping
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setAngularDamping
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    getAngularDamping
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_getAngularDamping
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setLinearDamping
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setLinearDamping
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    getLinearDamping
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_getLinearDamping
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setLinearVelocity
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setLinearVelocity
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setAngularVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setAngularVelocity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setAngle
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setAngle
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    getAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_getAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setAllowSleep
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setAllowSleep
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    isAllowSleep
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_isAllowSleep
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setPosition
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setPosition__Lcom_wiyun_engine_types_WYPoint_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setBullet
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setBullet
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    isBullet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_isBullet
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setGravityScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setGravityScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    getGravityScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_getGravityScale
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setFixedRotation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setFixedRotation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    isFixedRotation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_isFixedRotation
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    nativeGetPosition
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_nativeGetPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    getUserData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_getUserData
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_BodyDef
 * Method:    setUserData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_BodyDef_setUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
