/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_joints_GearJointDef */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_joints_GearJointDef
#define _Included_com_wiyun_engine_box2d_dynamics_joints_GearJointDef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    setJoint1
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/joints/Joint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_setJoint1
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    getJoint1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_getJoint1
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    setJoint2
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/joints/Joint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_setJoint2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    getJoint2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_getJoint2
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    setRatio
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_setRatio
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_GearJointDef
 * Method:    getRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_GearJointDef_getRatio
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
