/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_joints_JointDef */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_joints_JointDef
#define _Included_com_wiyun_engine_box2d_dynamics_joints_JointDef
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_UNKNOWN 0L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_REVOLUTE
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_REVOLUTE 1L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_PRISMATIC
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_PRISMATIC 2L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_DISTANCE
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_DISTANCE 3L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_PULLEY
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_PULLEY 4L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_MOUSE
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_MOUSE 5L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_GEAR
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_GEAR 6L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_LINE
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_LINE 7L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_WELD
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_WELD 8L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_FRICTION
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_FRICTION 9L
#undef com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_ROPE
#define com_wiyun_engine_box2d_dynamics_joints_JointDef_TYPE_ROPE 10L
/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    setBodyA
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/Body;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_setBodyA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    setBodyB
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/Body;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_setBodyB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    setCollideConnected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_setCollideConnected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    isCollideConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_isCollideConnected
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    nativeGetBodyA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_nativeGetBodyA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_JointDef
 * Method:    nativeGetBodyB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_JointDef_nativeGetBodyB
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
