/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_joints_PulleyJoint */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
#define _Included_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
 * Method:    nativeGetGroundAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint_nativeGetGroundAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
 * Method:    nativeGetGroundAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint_nativeGetGroundAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
 * Method:    getLength1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint_getLengthA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
 * Method:    GetLength2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint_getLengthB
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJoint
 * Method:    GetRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJoint_getRatio
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
