/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
#define _Included_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_UNKNOWN 0L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_REVOLUTE
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_REVOLUTE 1L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_PRISMATIC
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_PRISMATIC 2L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_DISTANCE
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_DISTANCE 3L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_PULLEY
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_PULLEY 4L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_MOUSE
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_MOUSE 5L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_GEAR
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_GEAR 6L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_LINE
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_LINE 7L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_WELD
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_WELD 8L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_FRICTION
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_FRICTION 9L
#undef com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_ROPE
#define com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_TYPE_ROPE 10L
/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    initialize
 * Signature: (Lcom/wiyun/engine/box2d/dynamics/Body;Lcom/wiyun/engine/box2d/dynamics/Body;Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;Lcom/wiyun/engine/types/WYPoint;F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_initialize
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setGroundAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setGroundAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setGroundAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setGroundAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setLocalAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setLocalAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setLocalAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setLocalAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    nativeGetGroundAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_nativeGetGroundAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    nativeGetGroundAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_nativeGetGroundAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    nativeGetLocalAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_nativeGetLocalAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    nativeGetLocalAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_nativeGetLocalAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setLengthA
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setLengthA
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    getLengthA
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_getLengthA
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setLengthB
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setLengthB
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    getLengthB
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_getLengthB
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    setRatio
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_setRatio
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef
 * Method:    getRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_PulleyJointDef_getRatio
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
