/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_joints_RopeJointDef */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
#define _Included_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_UNKNOWN 0L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_REVOLUTE
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_REVOLUTE 1L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_PRISMATIC
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_PRISMATIC 2L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_DISTANCE
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_DISTANCE 3L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_PULLEY
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_PULLEY 4L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_MOUSE
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_MOUSE 5L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_GEAR
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_GEAR 6L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_LINE
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_LINE 7L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_WELD
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_WELD 8L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_FRICTION
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_FRICTION 9L
#undef com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_ROPE
#define com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_TYPE_ROPE 10L
/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    setLocalAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_setLocalAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    setLocalAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_setLocalAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    nativeGetLocalAnchorA
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_nativeGetLocalAnchorA
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    nativeGetLocalAnchorB
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_nativeGetLocalAnchorB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    setMaxLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_setMaxLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_RopeJointDef
 * Method:    getMaxLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_RopeJointDef_getMaxLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
