/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_box2d_dynamics_joints_MouseJointDef */

#ifndef _Included_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
#define _Included_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_UNKNOWN
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_UNKNOWN 0L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_REVOLUTE
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_REVOLUTE 1L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_PRISMATIC
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_PRISMATIC 2L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_DISTANCE
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_DISTANCE 3L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_PULLEY
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_PULLEY 4L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_MOUSE
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_MOUSE 5L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_GEAR
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_GEAR 6L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_LINE
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_LINE 7L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_WELD
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_WELD 8L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_FRICTION
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_FRICTION 9L
#undef com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_ROPE
#define com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_TYPE_ROPE 10L
/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    nativeNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    setTarget
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_setTarget
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    nativeGetTarget
 * Signature: (Lcom/wiyun/engine/types/WYPoint;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_nativeGetTarget
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    setMaxForce
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_setMaxForce
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    getMaxForce
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_getMaxForce
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    setFrequencyHz
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_setFrequencyHz
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    getFrequencyHz
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_getFrequencyHz
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    setDampingRatio
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_setDampingRatio
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_wiyun_engine_box2d_dynamics_joints_MouseJointDef
 * Method:    getDampingRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_box2d_dynamics_joints_MouseJointDef_getDampingRatio
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
