// Auto generated by convert.sh in shaders folder
#define common_position_color_fsh " \
	#ifdef GL_ES\n \
		precision lowp float;\n \
	#endif\n \
	\n \
	#ifdef GL_ES\n \
		varying lowp vec4 v_fragmentColor;\n \
	#else\n \
		varying vec4 v_fragmentColor;\n \
	#endif\n \
	\n \
	void main() {\n \
		gl_FragColor = v_fragmentColor;\n \
	}"
