// Auto generated by convert.sh in shaders folder
#define common_position_texture_color_fsh " \
	#ifdef GL_ES\n \
		precision lowp float;\n \
	#endif\n \
	\n \
	#ifdef GL_ES\n \
		varying lowp vec4 v_fragmentColor;\n \
		varying mediump vec2 v_texCoord;\n \
	#else\n \
		varying vec4 v_fragmentColor;\n \
		varying vec2 v_texCoord;\n \
	#endif\n \
	uniform sampler2D u_texture2d;\n \
	\n \
	void main() {\n \
		gl_FragColor = v_fragmentColor * texture2D(u_texture2d, v_texCoord);\n \
	}"
