/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_grid_GridController */

#ifndef _Included_com_wiyun_engine_grid_GridController
#define _Included_com_wiyun_engine_grid_GridController
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    nativeAfterDraw
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_grid_GridController_nativeAfterDraw
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    beforeDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_grid_GridController_beforeDraw
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    getGridHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_grid_GridController_getGridHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    getGridWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_grid_GridController_getGridWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    getStepWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_grid_GridController_getStepWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    getStepHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_grid_GridController_getStepHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_grid_GridController_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    addReuseCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_grid_GridController_addReuseCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    reuse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_grid_GridController_reuse
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    isReuseGrid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_grid_GridController_isReuseGrid
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_grid_GridController
 * Method:    setActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_grid_GridController_setActive
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
